import React from "react";
import { AlertTriangle, ExternalLink, PackageSearch, ShieldCheck } from "lucide-react";

export type ProductSpecification = { label: string; value: string; conflict?: boolean };
export type ProductListing = { id: string; title: string; merchant: string | null; priceText: string | null; rating: number | null; reviews: number | null; imageUrl: string | null; productUrl: string | null; delivery: string | null; availability: string | null; completeness: "complete" | "partial" | "unverified"; policy: "eligible" | "approval_needed" | "blocked" | "unverified"; specificationStatus?: "idle" | "loading" | "sourced" | "unavailable"; specificationSource?: "marketplace" | "page" | "template"; specificationProfile?: "laptop" | "motorcycle" | "generic"; specifications?: ProductSpecification[]; recordKind?: "laptop_challenge_template"; bestMatch?: boolean; matchSummary?: string };
export type ProductListingViewState = { status: "idle" | "loading" | "live" | "fallback"; message?: string; listings: ProductListing[] };
export type ProductSearchGuidance = { title: string; copy: string; tone: "fallback" | "empty" } | null;

export const productPolicyMeta = {
  eligible: { label: "Eligible", cardTone: "border-[#1aae39]/30", badgeTone: "bg-[#effaf1] text-[#14752b]", explanation: "Within the confirmed price and authority limits." },
  approval_needed: { label: "Approval needed", cardTone: "border-[#dd5b00]/30", badgeTone: "bg-[#fff5ed] text-[#9a3b00]", explanation: "Within budget, but above the authority boundary." },
  blocked: { label: "Blocked", cardTone: "border-[#ff64c8]/35", badgeTone: "bg-[#fff1fa] text-[#9b2164]", explanation: "Unavailable or above the confirmed price ceiling." },
  unverified: { label: "Unverified", cardTone: "border-[#a39e98]/35", badgeTone: "bg-[#f6f5f4] text-[#615d59]", explanation: "A decision-critical marketplace field is missing; verify the page and seller before procurement." },
} as const;

export function summarizeProductListings(listings: ProductListing[]) {
  return listings.reduce((summary, listing) => ({ ...summary, [listing.policy]: summary[listing.policy] + 1 }), { eligible: 0, approval_needed: 0, blocked: 0, unverified: 0 });
}

export function prepareInitialMarketplaceListings<T extends ProductListing>(listings: T[]): Array<T & { specificationStatus: "sourced"; specificationSource: "marketplace" }> {
  return listings.map(listing => ({ ...listing, specificationStatus: "sourced" as const, specificationSource: "marketplace" as const }));
}

export function getInitialProductSearchState<T extends ProductListing>(listings: T[]) {
  return { listings: prepareInitialMarketplaceListings(listings), verificationRequest: null as null };
}

export function getExplicitFullVerificationRequest(category: string, listing: ProductListing) {
  if (!category.trim() || !listing.productUrl) return null;
  return { category: category.trim(), products: [{ id: listing.id, title: listing.title, productUrl: listing.productUrl }] };
}

export function getProductSearchGuidance(status: ProductListingViewState["status"], listingCount: number, localCandidateCount = 0, productCategory = "this request"): ProductSearchGuidance {
  if (listingCount > 0 || status === "loading" || status === "idle") return null;
  if (status === "fallback" && localCandidateCount > 0) return { tone: "fallback", title: "Marketplace cards are temporarily unavailable.", copy: `${localCandidateCount} labelled deterministic Vendor A/B candidate${localCandidateCount === 1 ? " is" : "s are"} available below for the local comparison. They are not live marketplace data. Try the marketplace search later or revise the confirmed requirements.` };
  if (status === "fallback") return { tone: "fallback", title: "Marketplace cards are temporarily unavailable.", copy: `No labelled deterministic Vendor A/B catalog covers ${productCategory}. The policy is correctly paused: retry live search later, revise the confirmed requirements, or use a supported curated demo. No vendor data was invented.` };
  return { tone: "empty", title: "No marketplace product cards matched this confirmed request.", copy: "Try widening the budget, delivery window, or specification. The app will not replace missing cards with unverified links." };
}

export function VendorOfferStatement({ listing }: { listing: ProductListing }) {
  const evidenceStatus = listing.recordKind === "laptop_challenge_template" ? "Deterministic demo record" : listing.completeness === "complete" ? "Reported terms" : listing.completeness === "partial" ? "Terms reported · verify stock" : "Incomplete · verify";
  const evidenceClass = listing.completeness === "complete" ? "text-[#31516f]" : "text-[#9a3b00]";
  const evidenceCopy = listing.recordKind === "laptop_challenge_template" ? "Pre-built laptop challenge template. Its values are deterministic demonstration data, not a live marketplace offer." : listing.completeness === "complete" ? "Marketplace fields are reported by the listing. Seller identity, stock, delivery, returns, and variant still require vendor confirmation before procurement." : listing.completeness === "partial" ? "The marketplace reported merchant, price, and a product page, but did not report stock. This card remains outside automatic recommendation until you verify current seller terms." : "The listing did not report core merchant, price, or product-page evidence. This card is excluded from automatic recommendation until you verify the product page and seller terms.";
  return <details className="border-t border-[#e6e6e6] bg-[#fdfdfc] px-4 py-3"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-[10px] font-bold uppercase tracking-[0.06em] text-[#615d59]"><span>Vendor evidence</span><span className={evidenceClass}>{evidenceStatus}</span></summary><dl className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-[11px]"><div><dt className="text-[#a39e98]">Reported merchant</dt><dd className="mt-0.5 font-semibold text-[#31302e]">{listing.merchant ?? "Not reported"}</dd></div><div><dt className="text-[#a39e98]">Quoted unit price</dt><dd className="mt-0.5 font-semibold text-[#31302e]">{listing.priceText ?? "Not reported"}</dd></div><div><dt className="text-[#a39e98]">Reported stock</dt><dd className="mt-0.5 font-semibold text-[#31302e]">{listing.availability ?? "Not reported by marketplace"}</dd></div><div><dt className="text-[#a39e98]">Reported delivery</dt><dd className="mt-0.5 font-semibold text-[#31302e]">{listing.delivery ?? "Not reported by marketplace"}</dd></div></dl><p className="mt-2 text-[10px] leading-4 text-[#615d59]">{evidenceCopy}</p></details>;
}

export function SpecificationPanel({ listing, onVerifyFullSpecifications }: { listing: ProductListing; onVerifyFullSpecifications?: (listing: ProductListing) => void }) {
  if (!listing.productUrl && !listing.specifications?.length) return null;
  const canVerify = listing.specificationSource !== "page" && Boolean(onVerifyFullSpecifications);
  if (listing.specificationStatus === "loading") return <div className="border-t border-[#e6e6e6] bg-[#f8fbfe] px-4 py-3"><p className="animate-pulse text-[11px] font-semibold text-[#005bab]">Verifying full specifications for this product…</p></div>;
  if (listing.specificationStatus === "unavailable") return <div className="border-t border-[#e6e6e6] bg-[#fdfdfc] px-4 py-3"><p className="text-[11px] leading-4 text-[#615d59]">Specifications unavailable from the product page. No values were inferred.</p>{onVerifyFullSpecifications && <button onClick={() => onVerifyFullSpecifications(listing)} className="mt-2 text-[11px] font-bold text-[#005bab] hover:underline">Retry full verification</button>}</div>;
  if (!listing.specifications?.length) return canVerify ? <div className="border-t border-[#e6e6e6] bg-[#fdfdfc] px-4 py-3"><p className="text-[11px] leading-4 text-[#615d59]">No concise specifications were present in the marketplace result. Full page verification may source product specifications, but stock, seller identity, delivery, returns, and the exact variant still require seller confirmation.</p><button onClick={() => onVerifyFullSpecifications?.(listing)} className="mt-2 text-[11px] font-bold text-[#005bab] hover:underline">Verify full page specifications</button></div> : null;
  const profileLabel = listing.specificationProfile === "motorcycle" ? "Motorcycle specifications" : listing.specificationProfile === "laptop" ? "Laptop specifications" : "Product specifications";
  const sourceLabel = listing.specificationSource === "template" ? "Challenge template" : listing.specificationSource === "marketplace" ? "Marketplace result" : "Sourced from page";
  return <details className="border-t border-[#e6e6e6] bg-[#f8fbfe] px-4 py-3"><summary className="flex cursor-pointer list-none items-center justify-between gap-2"><span className="text-[10px] font-bold uppercase tracking-[0.06em] text-[#005bab]">{profileLabel}</span><span className="text-[10px] font-semibold text-[#31516f]">{listing.specifications.length} field{listing.specifications.length === 1 ? "" : "s"} · {sourceLabel}</span></summary><dl className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-[11px]">{listing.specifications.map(specification => <div key={specification.label}><dt className="text-[#a39e98]">{specification.label}</dt><dd className="mt-0.5 font-semibold leading-4 text-[#31302e]">{specification.value}{specification.conflict && <span className="mt-1 block text-[10px] font-bold text-[#9a3b00]">Conflicting source values</span>}</dd></div>)}</dl><p className="mt-2 text-[10px] leading-4 text-[#31516f]">Page specifications are evidence only. Confirm seller identity, exact variant, stock, delivery, and returns before procurement.</p>{canVerify && <button onClick={() => onVerifyFullSpecifications?.(listing)} className="mt-3 text-[11px] font-bold text-[#005bab] hover:underline">Verify full page specifications</button>}</details>;
}

function ProductCard({ listing, onVerifyFullSpecifications }: { listing: ProductListing; onVerifyFullSpecifications?: (listing: ProductListing) => void }) {
  const policy = productPolicyMeta[listing.policy];
  return <article className={`flex min-h-full flex-col overflow-hidden rounded-xl border bg-[#fdfdfc] ${policy.cardTone}`}>{listing.bestMatch && <div className="bg-[#effaf1] px-4 py-2 text-[11px] font-bold text-[#14752b]">BEST MATCH FOR YOUR CONFIRMED REQUIREMENTS</div>}<div className="flex gap-3 p-4">{listing.imageUrl ? <img src={listing.imageUrl} alt="" className="h-22 w-22 shrink-0 rounded-lg border border-[#e6e6e6] bg-white object-contain" /> : <div className="grid h-22 w-22 shrink-0 place-items-center rounded-lg bg-[#f0efed] text-center text-[10px] font-bold text-[#615d59]">NO<br />IMAGE</div>}<div className="min-w-0 flex-1"><p className="line-clamp-3 text-[14px] font-bold leading-5 text-[#31302e]">{listing.title}</p><p className="mt-1 line-clamp-1 text-[12px] text-[#615d59]">{listing.merchant ?? "Merchant unavailable"}</p><p className="mt-2 text-[20px] font-bold tracking-[-0.4px] tabular-nums text-black">{listing.priceText ?? "Price unavailable"}</p></div></div>{listing.matchSummary && <p className="border-t border-[#e6e6e6] bg-[#f8fbfe] px-4 py-2 text-[11px] font-semibold leading-4 text-[#31516f]">{listing.matchSummary}</p>}<dl className="grid grid-cols-2 gap-x-3 gap-y-3 border-t border-[#e6e6e6] px-4 py-3 text-[11px]"><div><dt className="text-[#a39e98]">Availability</dt><dd className="mt-0.5 font-semibold text-[#31302e]">{listing.availability ?? "Not reported by marketplace"}</dd></div><div><dt className="text-[#a39e98]">Delivery</dt><dd className="mt-0.5 font-semibold text-[#31302e]">{listing.delivery ?? "Not reported by marketplace"}</dd></div><div><dt className="text-[#a39e98]">Rating</dt><dd className="mt-0.5 font-semibold text-[#31302e]">{listing.rating ? `${listing.rating}/5${listing.reviews ? ` · ${listing.reviews}` : ""}` : "Not reported by marketplace"}</dd></div><div><dt className="text-[#a39e98]">Evidence</dt><dd className="mt-0.5 font-semibold text-[#31302e]">{listing.recordKind === "laptop_challenge_template" ? "Demo template" : listing.completeness === "complete" ? "Core fields present" : listing.completeness === "partial" ? "Terms present · verify stock" : "Needs verification"}</dd></div></dl><VendorOfferStatement listing={listing} /><SpecificationPanel listing={listing} onVerifyFullSpecifications={onVerifyFullSpecifications} /><div className="mt-auto flex items-center justify-between gap-2 border-t border-[#e6e6e6] px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${policy.badgeTone}`}>{policy.label}</span>{listing.productUrl ? <a href={listing.productUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-[12px] font-bold text-[#005bab] hover:underline">Open listing <ExternalLink className="h-3.5 w-3.5" /></a> : <span className="text-[11px] font-semibold text-[#615d59]">Pre-built demo record</span>}</div></article>;
}

export default function ProductListingsPanel({ state, onVerifyFullSpecifications, policyAgreement, localCandidateCount = 0, productCategory }: { state: ProductListingViewState; onVerifyFullSpecifications?: (listing: ProductListing) => void; policyAgreement?: string; localCandidateCount?: number; productCategory?: string }) {
  if (state.status === "idle") return null;
  const summary = summarizeProductListings(state.listings);
  const hasListings = state.listings.length > 0;
  const guidance = getProductSearchGuidance(state.status, state.listings.length, localCandidateCount, productCategory);
  const statusTone = state.status === "live" ? "bg-white text-[#005bab]" : "bg-[#fff5ed] text-[#9a3b00]";
  const guidanceTone = guidance?.tone === "fallback" ? "border-[#dd5b00]/30 bg-[#fff5ed]" : "border-[#e6e6e6] bg-[#f6f5f4]";
  return <section aria-label="Marketplace product cards" className="mb-6 overflow-hidden rounded-2xl border border-[#0075de]/25 bg-white shadow-[0_1px_1px_rgba(0,0,0,.02),0_10px_26px_rgba(0,117,222,.07)]">
    <div className="border-b border-[#0075de]/15 bg-[#edf6ff] px-5 py-4 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-[#0075de] text-white"><PackageSearch className="h-5 w-5" /></span><div><p className="text-[11px] font-bold uppercase tracking-[0.08em] text-[#005bab]">Automatic marketplace product cards</p><h2 className="mt-0.5 text-[23px] font-bold tracking-[-0.5px] text-black">Products for your confirmed request.</h2><p className="mt-1 max-w-[760px] text-[12px] leading-5 text-[#31516f]">{state.status === "loading" ? "Searching marketplace records and checking policy limits…" : state.message ?? "Marketplace facts first. Full-page verification stays optional per product."}</p>{policyAgreement && <details className="mt-2 max-w-[820px] rounded-md border border-[#0075de]/20 bg-white/80 px-2.5 py-2 text-[11px] leading-4 text-[#31516f]"><summary className="cursor-pointer font-semibold text-[#005bab]">Confirmed policy agreement recorded</summary><p className="mt-1.5">{policyAgreement}</p></details>}</div></div><span className={`rounded-full px-3 py-1.5 text-[11px] font-bold ${statusTone}`}>{state.status === "loading" ? "Searching" : hasListings ? `${state.listings.length} products found` : "No cards returned"}</span></div></div>
    <div className="p-5 sm:p-6">{state.status === "loading" ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-[320px] animate-pulse rounded-xl border border-[#e6e6e6] bg-[#f6f5f4]" />)}</div> : hasListings ? <><div className="mb-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{(Object.keys(productPolicyMeta) as Array<keyof typeof productPolicyMeta>).map(policy => <div key={policy} className="rounded-lg border border-[#e6e6e6] bg-[#fdfdfc] px-3 py-2"><p className="text-[11px] font-semibold text-[#615d59]">{productPolicyMeta[policy].label}</p><p className="mt-0.5 text-[18px] font-bold tabular-nums text-black">{summary[policy]}</p></div>)}</div><details aria-label="Product policy legend" className="mb-4 rounded-lg border border-[#e6e6e6] bg-[#fdfdfc] px-3 py-2.5"><summary className="cursor-pointer text-[11px] font-semibold text-[#005bab]">How marketplace policy labels are applied</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{(Object.keys(productPolicyMeta) as Array<keyof typeof productPolicyMeta>).map(policy => <p key={policy} className="text-[11px] leading-4 text-[#615d59]"><strong className="text-[#31302e]">{productPolicyMeta[policy].label}:</strong> {productPolicyMeta[policy].explanation}</p>)}</div></details><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{state.listings.map(listing => <ProductCard key={listing.id} listing={listing} onVerifyFullSpecifications={onVerifyFullSpecifications} />)}</div></> : guidance ? <div className={`rounded-xl border p-5 ${guidanceTone}`}><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#a39e98] text-white">{guidance.tone === "fallback" ? <AlertTriangle className="h-4 w-4" /> : <PackageSearch className="h-4 w-4" />}</span><div><h3 className="text-[15px] font-bold text-[#31302e]">{guidance.title}</h3><p className="mt-1 max-w-[760px] text-[13px] leading-5 text-[#615d59]">{guidance.copy}</p></div></div></div> : null}<div className="mt-5 grid gap-3 border-t border-[#e6e6e6] pt-4 text-[11px] leading-5 text-[#615d59] md:grid-cols-[1fr_auto]"><p className="flex items-start gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#0075de]" />Policy labels use the requester-confirmed price ceiling and authority limit. Cards are not an order, payment, or approval action.</p><p className="font-semibold uppercase tracking-[0.06em] text-[#9a3b00]">Verify stock, seller, delivery, returns, and variant before procurement</p></div></div>
  </section>;
}
